version: '3.6'
services:
  account-translator:
    image: uscdev/front-end
    ports:
      - 4200:4200
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
