#  Create a new image from the base nodejs 8 image.
FROM node:8
# Patch it
RUN apt-get -y update && apt-get -y upgrade
# Create the target directory in the image
RUN mkdir -p /usr/src/app
# Set the created directory as the working directory
WORKDIR /usr/src/app
# Copy the package.json inside the working directory
COPY *.json /usr/src/app/
# Install required dependencies
RUN npm install
# Copy the client application source files. You can use .dockerignore to exclude files. Works just as .gitignore does.
#COPY webpack.config.js /usr/src/app

#RUN rm -rf _dist && ./node_modules/.bin/webpack


COPY . /usr/src/app
# ADD updateEnv.sh /usr/src/
# Open port 4200. This is the port that our development server uses
EXPOSE 4200
# Start the application. This is the same as running ng serve.

# USER node

CMD ["npm", "start"]
